# Setup
title: Joe's Memos
tagline: Health. Happiness. Heaven.
url: https://joesmemos.com
paginate: 3
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
 
sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Joseph Kreydt
  url: https:www.instagram.com/joesmemos
  email: none@gmail.com

# Custom vars
version: 3.0.0
